### ISSUE TITLE
Luxury Auto's

### ISSUE THREAD

**Issue by JimSteel1** [Derpystepdad/New-Beginnings-RP#3]
*Describe the feature you'd like*
I would like to have a Luxury Auto's in the city so there is another dealership for more RP

*Describe alternatives you've considered*
I think that I would just make better RP and more selection for cars

**Comment by Derpystepdad** [comment]
We are currently looking for an mlo for delux auto to add the imported cars too.

**Comment by Derpystepdad** [comment]
All import cars have been moved Delux auto's we are looking into another car shop to replace the one at PDM.
